image: "gitlab.autsoft.hu:4567/devops/androidciimage:latest"

########## Global settings ##########

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
  - .android/build-cache/

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

########## Job templates ##########

.build: &build
  stage: build
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:assembleRelease
      ${MODULE_NAME}:androidSourcesJar
      ${MODULE_NAME}:generatePomFileForReleasePublication
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours

.instrumentationTest: &instrumentationTest
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew autsoftInstrumentationTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.deployArtifactory: &deployArtifactory
  stage: deploy
  tags:
    - docker
  script:
    - ./gradlew ${MODULE_NAME}:uploadArchives
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

.deployBintray: &deployBintray
  stage: deploy
  tags:
    - docker
  script:
    - ./gradlew ${MODULE_NAME}:bintrayUpload
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

########## Concrete jobs ##########

### Build ###

krate build:
  <<: *build
  variables:
    MODULE_NAME: krate

krate-gson build:
  <<: *build
  variables:
    MODULE_NAME: krate-gson

### Tests ###

krate instrumentation test:
  <<: *instrumentationTest
  script:
    - ./gradlew krate:autsoftInstrumentationTest

krate-gson instrumentation test:
  <<: *instrumentationTest
  script:
    - ./gradlew krate-gson:autsoftInstrumentationTest

### Deployment ###

krate deploy to artifactory:
  <<: *deployArtifactory
  variables:
    MODULE_NAME: krate

krate deploy to bintray:
  <<: *deployBintray
  variables:
    MODULE_NAME: krate

krate-gson deploy to artifactory:
  <<: *deployArtifactory
  variables:
    MODULE_NAME: krate-gson

krate-gson deploy to bintray:
  <<: *deployBintray
  variables:
    MODULE_NAME: krate-gson
