image: registry.gitlab.com/hardysim/android-ci:latest

########## Global settings ##########

cache:
  paths:
    - .gradle
    - .android/build-cache/

stages:
  - build base library
  - build modules
  - demo app build
  - test
  - staging
  - release

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

########## Job templates ##########

debug build:
  tags:
    - docker
  script:
    - >
      ./gradlew assembleDebug
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

release build:
  tags:
    - docker
  script:
    - >
      ./gradlew
      krate:assembleRelease
      krate-gson:assembleRelease
      krate-moshi-stub:assembleRelease
      krate-moshi-core:assembleRelease
      krate-moshi-reflect:assembleRelease
      krate-moshi-codegen:assembleRelease
      krate:androidSourcesJar
      krate-gson:androidSourcesJar
      krate-moshi-stub:androidSourcesJar
      krate-moshi-core:androidSourcesJar
      krate-moshi-reflect:androidSourcesJar
      krate-moshi-codegen:androidSourcesJar
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

instrumentation test:
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew connectedDebugAndroidTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags
  dependencies:
    - debug build

stage to MavenCentral:
  stage: staging
  tags:
    - docker
  before_script:
    - echo $GPG_KEY_CONTENTS | base64 -d > /secret.gpg
    - ls -al /
  script:
    - ./gradlew publishReleasePublicationToSonatypeRepository
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/
  dependencies:
    - release build

release to MavenCentral:
  stage: release
  tags:
    - docker
  script:
    - ./gradlew closeAndReleaseRepository
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/
