image: "gitlab.autsoft.hu:4567/devops/androidciimage:latest"

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
  - .android/build-cache/

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

.build: &build
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleRelease androidSourcesJar generatePomFileForReleasePublication
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours

.instrumentationTest: &instrumentationTest
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew autsoftInstrumentationTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.deploy: &deploy
  stage: deploy
  tags:
    - docker
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours

########## Developer customised part

build:
  <<: *build

instrumentationTest:
  <<: *instrumentationTest

deploy to artifactory:
  <<: *deploy
  script:
    - ./gradlew uploadArchives
  only:
    - /^.*-RELEASE$/

deploy to bintray:
  <<: *deploy
  script:
    - ./gradlew bintrayUpload
  only:
    - /^.*-RELEASE$/
