image: "gitlab.autsoft.hu:4567/devops/androidciimage:latest"

########## Global settings ##########

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
  - .android/build-cache/

stages:
  - build base library
  - build modules
  - demo app builds
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

########## Job templates ##########

.debugBuild: &debugBuild
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:assembleDebug
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.releaseBuild: &releaseBuild
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:assembleRelease
      ${MODULE_NAME}:androidSourcesJar
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

.instrumentationTest: &instrumentationTest
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew ${MODULE_NAME}:autsoftInstrumentationTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.deployArtifactory: &deployArtifactory
  stage: deploy
  tags:
    - docker
  script:
    - ./gradlew ${MODULE_NAME}:uploadArchives
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

.deployBintray: &deployBintray
  stage: deploy
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:generatePomFileForReleasePublication
      ${MODULE_NAME}:bintrayUpload
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

########## Concrete jobs ##########

### Base library build ###

krate debug build:
  <<: *debugBuild
  stage: build base library
  variables:
    MODULE_NAME: krate

krate release build:
  <<: *releaseBuild
  stage: build base library
  variables:
    MODULE_NAME: krate

### Module library builds ###

krate-gson debug build:
  <<: *debugBuild
  stage: build modules
  variables:
    MODULE_NAME: krate-gson

krate-gson release build:
  <<: *releaseBuild
  stage: build modules
  variables:
    MODULE_NAME: krate-gson

### Demo app build ###

app debug build:
  <<: *debugBuild
  stage: demo app builds
  variables:
    MODULE_NAME: app

### Tests ###

krate instrumentation test:
  <<: *instrumentationTest
  variables:
    MODULE_NAME: krate

krate-gson instrumentation test:
  <<: *instrumentationTest
  variables:
    MODULE_NAME: krate-gson

### Deployment ###

krate deploy to artifactory:
  <<: *deployArtifactory
  variables:
    MODULE_NAME: krate

krate deploy to bintray:
  <<: *deployBintray
  variables:
    MODULE_NAME: krate

krate-gson deploy to artifactory:
  <<: *deployArtifactory
  variables:
    MODULE_NAME: krate-gson

krate-gson deploy to bintray:
  <<: *deployBintray
  variables:
    MODULE_NAME: krate-gson
